### ISSUE TITLE
Basic Driving Robot

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/BionicFramework#67]
## Description of Changes Requested
I'd like for a basic driving robot, complete with a drivetrain and operator interface.

## Task List
- [x] Instantiate Drivetrain w/ Left Motor:`Spark(0)` & Right Motor: `Spark(1)`
- [x] Configure -1.0 Rotation Constant
- [x] Instantiate Driver Gamepad
- [x] Instantiate Axes for Speed (LY) & Rotation (RX)
- [x] Create Buttons for Direction Forward (A) & Reverse(Y)

## Feature Request Contact (for addt. questions)
@roshanr10
